/* eslint-disable react-refresh/only-export-components */
import "./index.css";
import "./i18n";

export {
  // Desktop相关
  Desktop,
  DesktopSortable,
  DesktopAppItem,
  DesktopGroupItem,
  DesktopBaseModal,
  DesktopBaseDrawer,
  DesktopSortableConfigProvider,
  DesktopSortableStateProvider,
  getDesktopDefaultConfig,
  desktopThemeLight,
  desktopThemeDark,
  SortableUtils,
  DesktopNext,
  desktopNextCommonSizeConfigs,
  desktopNextAppDefaultConfig,
  desktopNextGroupDefaultConfig,
  desktopNextBuiltinConfigMap,
  getDesktopNextDefaultConfig,
  getDesktopNextSizeConfig,
  getDesktopNextItemSize,
  desktopNextThemeLight,
  desktopNextThemeDark,
  desktopNextDefaultTheme,
  desktopNextThemes,
  DesktopDnd,
  desktopDndCommonSizeConfigs,
  desktopDndAppDefaultConfig,
  desktopDndGroupDefaultConfig,
  desktopDndBuiltinConfigMap,
  getDesktopDndDefaultConfig,
  getDesktopDndSizeConfig,
  getDesktopDndItemSize,

  // Dock相关
  Dock,
  DockDesktop,
  DockDesktopItem,
  DockMobile,
  DockMobileItem,
  useDockDesktopMouseX,

  // 其他组件
  MdEditor,
  Markdown,
  GeoMap,
  SimpleEditor,
  SimpleEditorViewer,
  useSimpleEditor,
  jsonToHtml,
  htmlToJson,
  EditorFormatConverter,
  PhotoWatermark,
  HtmlRenderer,
  availableTemplates,
  extractExifData,
  parseExifData,
  formatXiaomiLeicaExifData,

  IdPhotoChecker,
  useIdPhotoChecker,
} from "./components";

export type {
  DesktopHandle,
  DesktopProps,
  DesktopAppItemProps,
  DesktopGroupItemProps,
  DesktopSortableProps,
  DesktopSortableConfigProviderProps,
  DesktopSortableStateProviderProps,
  DesktopBaseModalProps,
  DesktopBaseDrawerProps,
  DesktopSortItemBaseConfig,
  DesktopSortItemUserConfig,
  DesktopSortItemDefaultConfig,
  DesktopTypeConfigMap,
  DesktopSortItem,
  DesktopListItem,
  DesktopSortItemBaseData,
  DesktopTheme,
  DesktopNextProps,
  DesktopNextContextMenuProps,
  DesktopNextTheme,
  DesktopNextThemeType,
  DesktopDndProps,
  DndSortItem,
  DndPageItem,
  DndItemBaseData,
  SizeConfig,
  SortItemUserConfig,
  MenuItemConfig,
  DataTypeMenuConfigMap,
  SortItemDefaultConfig,
  TypeConfigMap,
  ContextMenuData,
  DesktopDndContextMenuProps,
  ContextMenuActionPayload,
  ContextMenuActionType,

  // Dock相关类型
  DockDesktopItemProps,
  DockMobileItemProps,

  // SimpleEditor相关类型
  SimpleEditorProps,
  SimpleEditorViewerProps,
  SimpleEditorFeatures,
  EditorOutputFormat,
  UseSimpleEditorProps,
  JSONContent,
  ExifData,
  ExifExtractResult,

  // IdPhotoChecker相关类型
  IdPhotoCheckerProps,
  UseIdPhotoCheckerReturn,
  IdPhotoValidationResult,
  IdPhotoValidationItem,
  IdPhotoValidationStatus,
  IdPhotoRuleConfig,
  IdPhotoBoundsConfig,
  IdPhotoThresholdConfig,
  IdPhotoCameraConfig,
  IdPhotoMessageConfig,
} from "./components";

// 导出所有组件作为默认导出
import * as Components from "./components";
export default Components;
