/* eslint-disable react-refresh/only-export-components */
import "./index.css";
import "./i18n";

export {
  // Desktop相关
  Desktop,
  DesktopSortable,
  DesktopAppItem,
  DesktopGroupItem,
  DesktopBaseModal,
  DesktopBaseDrawer,
  DesktopSortableConfigProvider,
  DesktopSortableStateProvider,
  getDesktopDefaultConfig,
  desktopThemeLight,
  desktopThemeDark,
  SortableUtils,
  DesktopNext,
  DesktopNextProvider,
  useDesktopNext,
  DesktopNextActionsProvider,
  DesktopNextConfigProvider,
  DesktopNextStateProvider,
  useDesktopNextActions,
  useDesktopNextConfig,
  useDesktopNextState,
  DesktopNextContextMenu,
  DesktopNextContextMenuItem,
  DesktopNextContextMenuSubMenuItem,
  DesktopNextContextMenuSizeSubMenuContent,
  DesktopNextContextMenuHoverContext,
  DesktopNextDock,
  DesktopNextLaunchpadModal,
  DesktopNextLaunchpadButton,
  DesktopNextStackedIcon,
  DesktopNextSearchBox,
  DesktopNextBaseModal,
  DesktopNextBaseDrawer,
  loadDesktopNextRemoteComponent,
  DesktopNextRemoteComponentErrorBoundary,
  mergeDesktopNextTheme,
  desktopNextCommonSizeConfigs,
  desktopNextCommonSizeConfigsArray,
  desktopNextAppDefaultConfig,
  desktopNextGroupDefaultConfig,
  desktopNextBuiltinConfigMap,
  getDesktopNextDefaultConfig,
  getDesktopNextSizeConfig,
  getDesktopNextItemSize,
  getDesktopNextDataTypeMenuConfig,
  desktopNextThemeLight,
  desktopNextThemeDark,
  desktopNextDefaultTheme,
  desktopNextThemes,
  DesktopDnd,
  desktopDndCommonSizeConfigs,
  desktopDndAppDefaultConfig,
  desktopDndGroupDefaultConfig,
  desktopDndBuiltinConfigMap,
  getDesktopDndDefaultConfig,
  getDesktopDndSizeConfig,
  getDesktopDndItemSize,

  // Dock相关
  Dock,
  DockDesktop,
  DockDesktopItem,
  DockMobile,
  DockMobileItem,
  useDockDesktopMouseX,

  // 其他组件
  MdEditor,
  Markdown,
  GeoMap,
  SimpleEditor,
  SimpleEditorViewer,
  useSimpleEditor,
  jsonToHtml,
  htmlToJson,
  EditorFormatConverter,
  PhotoWatermark,
  HtmlRenderer,
  availableTemplates,
  extractExifData,
  parseExifData,
  formatXiaomiLeicaExifData,
} from "./components";

export type {
  DesktopHandle,
  DesktopProps,
  DesktopAppItemProps,
  DesktopGroupItemProps,
  DesktopSortableProps,
  DesktopSortableConfigProviderProps,
  DesktopSortableStateProviderProps,
  DesktopBaseModalProps,
  DesktopBaseDrawerProps,
  DesktopSortItemBaseConfig,
  DesktopSortItemUserConfig,
  DesktopSortItemDefaultConfig,
  DesktopTypeConfigMap,
  DesktopSortItem,
  DesktopListItem,
  DesktopSortItemBaseData,
  DesktopTheme,
  DesktopNextProps,
  DesktopNextHandle,
  DesktopNextProviderProps,
  DesktopNextActionsContextValue,
  DesktopNextConfigContextValue,
  DesktopNextContextValue,
  DesktopNextStateContextValue,
  DesktopNextContextMenuProps,
  DesktopNextContextMenuComponentProps,
  DesktopNextContextMenuItemProps,
  DesktopNextContextMenuSubMenuItemProps,
  DesktopNextContextMenuSizeMenuItemProps,
  DesktopNextContextMenuHoverContextType,
  DesktopNextDockProps,
  DesktopNextLaunchpadModalProps,
  DesktopNextLaunchpadButtonProps,
  DesktopNextStackedIconProps,
  DesktopNextSearchBoxProps,
  DesktopNextBaseModalProps,
  DesktopNextBaseDrawerProps,
  DesktopNextTheme,
  DesktopNextThemeType,
  DesktopDndProps,
  DndSortItem,
  DndPageItem,
  DndItemBaseData,
  SizeConfig,
  SortItemUserConfig,
  MenuItemConfig,
  DataTypeMenuConfigMap,
  SortItemDefaultConfig,
  TypeConfigMap,
  ContextMenuData,
  DesktopDndContextMenuProps,
  ContextMenuActionPayload,
  ContextMenuActionType,
  DesktopNextListItem,
  DesktopNextSortItemBaseData,
  DesktopNextSortItemBaseConfig,
  DesktopNextComponentRegistryEntry,
  DesktopNextComponentRegistry,
  DesktopNextPageTransition,

  // Dock相关类型
  DockDesktopItemProps,
  DockMobileItemProps,

  // SimpleEditor相关类型
  SimpleEditorProps,
  SimpleEditorViewerProps,
  SimpleEditorFeatures,
  EditorOutputFormat,
  UseSimpleEditorProps,
  JSONContent,
  ExifData,
  ExifExtractResult,
} from "./components";

// 导出所有组件作为默认导出
import * as Components from "./components";
export default Components;
